### ISSUE TITLE
Incorrect README output by pandoc

### ISSUE THREAD

**Issue by tanjot** [tanjot/trimfilename#16]
Output in html format does not show proper formatting. Following is a part of output
# Trim Filename

|Stories in Ready|

| A script to trim a specific pattern from filenames.
| Files are recursively checked for a pattern match on the path user
mentions.

Usage
^^^^^

.. code:: sh

**Comment by ylogx** [comment]
Use following command to see warnings.

```
pandoc --from=markdown --to=rst --output=README.rst README.md && python /usr/bin/rst2html.py README.rst > readme.html
```

Fix each of these warnings to get correct output on pypi

**Comment by ylogx** [comment]
See these commits:

https://github.com/shubhamchaudhary/logmein/commit/a077ffa16589543d431aebf3995e6aff638d924c

https://github.com/shubhamchaudhary/logmein/commit/6e1e7592e1712f9dfb97126a2d2c18655b8d5fa4

**Comment by tanjot** [comment]
It ate a lot of time but finally I found I did not have docutils installed, hence, no warnings were displayed: **pip install docutils**

Finally , removed the warnings @6d8219263d6558577a78be492064ede7da785dc9
